POST https://localhost:7150/api/admin/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userName": "test_user",
    "lastName": "Johnson",
    "firstName": "Michael"
}
###
GET https://localhost:7150/api/admin/users
Content-Type: application/json
Authorization: Bearer {{token}} 
###
GET https://localhost:7150/api/admin/users?search=admin
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET https://localhost:7150/api/admin/users?search=UserName:admin
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET https://localhost:7150/api/admin/users?sort=asc(UserName)
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET https://localhost:7150/api/admin/users?sort=asc(username),desc(firstname)
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET https://localhost:7150/api/admin/users/d3f67070-a5e9-4891-bd64-be10f81888d9
Content-Type: application/json
Authorization: Bearer {{token}}
###
PUT https://localhost:7150/api/admin/users/2f0ff955-3ee1-4b41-a392-68f3e9d01626
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userName": "test_u",
    "lastName": "lastname updated",
    "firstName": "firstname updated"
}
###
DELETE https://localhost:7150/api/admin/users/2f0ff955-3ee1-4b41-a392-68f3e9d01626
Content-Type: application/json
Authorization: Bearer {{token}}
